name: Build & Push Docker Images ğŸ³

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ğŸ“¥
        uses: actions/checkout@v3

      - name: Login to Docker Hub ğŸ³
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR âš¡
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image ğŸ”¨
        run: |
          docker build -t nginx-party:latest .
          docker tag nginx-party:latest ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:latest
          docker tag nginx-party:latest ghcr.io/${{ github.repository_owner }}/nginx-party:latest

      - name: Push Docker images ğŸš€
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:latest
          docker push ghcr.io/${{ github.repository_owner }}/nginx-party:latest
