name: ğŸ³ NGINX-PARTY Docker Build & Push âš¡ğŸ› ï¸

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: âš¡ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ¼ Build Docker Image
        run: |
          docker build -t nginx-party-stable:latest .
      
      - name: ğŸš€ Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: ğŸ·ï¸ Push GHCR Image
        run: |
          docker tag nginx-party-stable:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/nginx-party-stable:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/nginx-party-stable:latest

      - name: ğŸš€ Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ·ï¸ Push Docker Hub Image
        run: |
          docker tag nginx-party-stable:latest ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party-stable:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party-stable:latest