name: ğŸ³ PANDUH-PARTY Docker Build âš¡ğŸ•¶ï¸ğŸŒ

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ¼ Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: ğŸ’¾ Restore NGINX build cache
        uses: actions/cache@v4
        with:
          path: /usr/local/nginx
          key: nginx-build-${{ env.NGINX_VERSION }}

      - name: ğŸ”§ Build Docker image
        run: |
          docker build \
            --build-arg NGINX_PATH=/usr/local/nginx \
            -t ${{ secrets.DOCKER_HUB_USER }}/nginx-party:stable \
            -t ghcr.io/${{ github.repository }}/nginx-party:stable \
            .

      - name: ğŸš€ Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/nginx-party:stable
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}

      - name: ğŸš€ Push to GHCR
        run: docker push ghcr.io/${{ github.repository }}/nginx-party:stable
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
