name: ğŸ³ Docker NGINX-PARTY

on:
  workflow_dispatch:

jobs:
  docker:
    name: âš¡ Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ğŸ“¥ Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx-party:stable
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nginx-party:stable