name: "ğŸ³ Docker Build & Push"
on:
  workflow_dispatch:

jobs:
  docker:
    name: "ğŸ³ Build & Push Docker"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "ğŸ“¥ Checkout Repo"
        uses: actions/checkout@v4

      - name: "ğŸ³ Log in to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "ğŸ³ Log in to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "ğŸ³ Build & Push Docker Image"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nginx-party:latest
            ${{ secrets.DOCKER_USERNAME }}/nginx-party:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/nginx-party:latest
            ghcr.io/${{ github.repository_owner }}/nginx-party:${{ github.sha }}