name: ğŸ¼ Docker Build & Push ğŸ‹

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  NGINX_VERSION: 1.29.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¼ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ—„ï¸ Restore ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: docker-${{ env.NGINX_VERSION }}-${{ github.sha }}

      - name: ğŸ‹ Build Docker Image
        run: |
          docker build \
            --build-arg NGINX_VERSION=${NGINX_VERSION} \
            -t ghcr.io/${{ github.repository }}/nginx-party:${{ github.sha }} .

      - name: ğŸ“¤ Push Docker Image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}/nginx-party:${{ github.sha }}