name: PANDUH-PARTY Docker Build ğŸ³ğŸš€ğŸ’¾

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: âš¡ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ¼ Build Docker Image
        run: |
          docker build -t panduh-party:latest .

      - name: ğŸ” Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: ğŸš€ Push to GitHub Container Registry
        run: |
          docker tag panduh-party:latest ghcr.io/${{ github.repository }}/panduh-party:latest
          docker push ghcr.io/${{ github.repository }}/panduh-party:latest

      - name: ğŸ” Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸš€ Push to Docker Hub
        run: |
          docker tag panduh-party:latest ${{ secrets.DOCKER_USERNAME }}/panduh-party:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/panduh-party:latest
