name: Build & Push Docker Images ğŸ³

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo ğŸ“¥
        uses: actions/checkout@v3

      - name: Download CI-built .deb artifact ğŸ“¦
        uses: actions/download-artifact@v4
        with:
          name: nginx-party-deb
          path: ./deb

      - name: Login to Docker Hub ğŸ³
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR âš¡
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image ğŸ”¨
        run: |
          cp ./deb/nginx-party*.deb ./Dockerfile-root/
          docker build -t nginx-party:latest ./Dockerfile-root
          docker tag nginx-party:latest ${{ secrets.DOCKER_USERNAME }}/nginx-party:latest
          docker tag nginx-party:latest ghcr.io/${{ github.repository_owner }}/nginx-party:latest

      - name: Push Docker images ğŸš€
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-party:latest
          docker push ghcr.io/${{ github.repository_owner }}/nginx-party:latest
