name: ğŸ³ NGINX-PARTY Docker Build + Push ğŸš€âœ¨

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: nginx-party
      TAG: stable
    
    steps:
      - name: ğŸ¼ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}

      - name: ğŸ› ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ”§ Build Docker image
        run: |
          docker buildx build \
            --build-arg NGINX_VERSION=1.29.1 \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t $IMAGE_NAME:$TAG \
            -t ghcr.io/${{ github.repository }}:$TAG \
            .

      - name: ğŸ” Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: ğŸ” Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸš€ Push images
        run: |
          docker push $IMAGE_NAME:$TAG
          docker push ghcr.io/${{ github.repository }}:$TAG
