name: ğŸ³ NGINX-PARTY Docker (ğŸš€ Stable + QUIC + Mods)

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ³ Build Docker image
        run: |
          docker build \
            --build-arg NGINX_VERSION=1.29.1 \
            --build-arg OPENSSL_VERSION=3.3.1 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:stable .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:stable \
            ghcr.io/${{ github.repository_owner }}/nginx-party:stable

      - name: ğŸš€ Push DockerHub image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:stable

      - name: ğŸš€ Push GHCR image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/nginx-party:stable