name: ğŸ³ Docker Build & Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    name: âš¡ Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ³ Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:latest ghcr.io/${{ github.repository_owner }}/nginx-party:latest

      - name: ğŸš€ Push to Docker Hub & GHCR
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/nginx-party:latest