name: ğŸ³ Docker Build & Push

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ§ Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:stable .

      - name: ğŸš€ Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:stable

      - name: ğŸ“¦ Push to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:stable ghcr.io/${{ github.repository }}/nginx-party:stable
          docker push ghcr.io/${{ github.repository }}/nginx-party:stable