name: ğŸ³ PANDUH-PARTY Docker Build & Push

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ğŸ”„ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Build Docker Image
        run: |
          docker build -t nginx-party:stable .
      
      - name: ğŸš€ Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: ğŸš€ Push to GHCR
        run: docker tag nginx-party:stable ghcr.io/${{ github.repository_owner }}/nginx-party:stable && docker push ghcr.io/${{ github.repository_owner }}/nginx-party:stable

      - name: ğŸš€ Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸš€ Push to Docker Hub
        run: docker tag nginx-party:stable ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:stable && docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:stable