name: "ğŸ³ Docker Build & Push"

on:
  workflow_dispatch:

jobs:
  docker:
    name: "ğŸ³ Build & Push Docker"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "ğŸ“¥ Checkout Repo"
        uses: actions/checkout@v4

      - name: "ğŸ³ Build & Push Docker Images"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nginx-party:stable
            ghcr.io/${{ github.repository_owner }}/nginx-party:stable
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}